version: '3'
services:
 transmission:
  image: tgcustom
  container_name: tgvpn3
  cap_add:
    - NET_ADMIN
  devices:
    - /dev/net/tun
  restart: always
  ports:
    - "9091:9091"
    - "8888:8888"
  dns:
    - 4.4.4.4
  volumes:
    - /Users/ronaldmendoza/docker/srv1/data:/data
    - /Users/ronaldmendoza/docker/srv1/config:/config
  sysctls:
    - net.ipv6.conf.all.disable_ipv6=1
  environment:
    - CREATE_TUN_DEVICE=true
    - OPENVPN_PROVIDER=TORGUARD
    - OPENVPN_CONFIG=USA-SAN-FRANCISCO
    - LOCAL_NETWORK=192.168.0.0/16
    - HEALTH_CHECK_HOST=192.168.104.10
    - WEBPROXY_ENABLED=true
